[package]
name = "domain"
version = "0.1.0"
authors = ["ryutah <6662577+ryutah@users.noreply.github.com>"]
edition = "2018"

[dependencies]
derive-getters = "0.2.0"
derive-new = "0.5.9"
libmww = { path = "../libmww" }
anyhow = "1.0.40"
async-trait = "0.1.50"

[dev-dependencies]
test-case = "1.1.0"
