name: CARRIAGE
on: [push]
jobs:
  rust-lint:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/mwwolf/mwwolf/rust_test:1.0.0
      credentials:
        username: ${{ secrets.GH_PACKAGE_READ_USER }}
        password: ${{ secrets.GH_PACKAGE_READ_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: scripts/lint/lint_rust.sh

  rust-test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/mwwolf/mwwolf/rust_test:1.0.0
      credentials:
        username: ${{ secrets.GH_PACKAGE_READ_USER }}
        password: ${{ secrets.GH_PACKAGE_READ_TOKEN }}
      env:
        GOOGLE_CLOUD_PROJECT: mwwolf-local
        DATASTORE_EMULATOR_HOST: "localhost:61000"
    services:
      datastore:
        image: docker.pkg.github.com/mwwolf/mwwolf/datastore:1.0.2
        credentials:
          username: ${{ secrets.GH_PACKAGE_READ_USER }}
          password: ${{ secrets.GH_PACKAGE_READ_TOKEN }}
        ports:
          - 61000:61000
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: scripts/test/test_rust.sh
env:
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always
  WORKSPACE_ROOT: "/__w/mwwolf/mwwolf"
